
export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_PROVIDERS = 'FETCH_PROVIDERS';
export const SHOW_NEWSLIST  = 'SHOW_NEWSLIST';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const SHOW_WEATHER = 'SHOW_WEATHER';
export const FETCH_PARKING = 'FETCH_PARKING';
export const SHOW_PARKING = 'SHOW_PARKING';
export const GET_SELECTEDPARK = 'GET_SELECTEDPARK';
